### PR TITLE
Fix clippy lints

### PR DESCRIPTION
**Pull request by 0e4ef622**
Replace `std::*::EPSILON` with `*::EPSILON`, etc.

### CODE REVIEW

**Comment by 0e4ef622** [comment]
Not exactly sure what to do about the remaining CI failures.

**Comment by stefan-k** [comment]
Thanks for your work and apologies for the long wait!

The argmin-math tests are broken due to #509, will have to fix that in another PR or I may just do it in this one.

**Comment by stefan-k** [comment]
Fixes #509

**Review by stefan-k — APPROVED** [review]
Thanks for your work! :)

**Pull request merged**
