### PR TITLE
[fix] simulated anneal always accepts first iter

### PR DESCRIPTION
**Pull request by dariogoetz**
This addresses #150 

It appears to me that the initial `ArgminIterData` returned by the simulated anneal solver's `init` method does not contain values for `param` and `cost`. Hence the `executor`'s state is not being updated upon calling the `solver`'s `init` method. This leads to the state having infinity as starting cost, which makes any first solution preferable.

I have added param and corresponding initial cost to the solver's init method.

### CODE REVIEW

**Comment by stefan-k** [comment]
Thank you for this PR! This is actually what I also suspected, apologies that I wasn't able to address this  myself.

For some reason the CI is broken since yesterday. I'm having the same problem in #152. I will try to have a look hopefully this evening. My suspicion is that something in the images changed.

**Comment by dariogoetz** [comment]
Don't worry, it was not my intention to apply any pressure to you. I just wanted to offer my help with the PR.

**Comment by stefan-k** [comment]
I did not interpret this as pressure :) Any help is highly appreciated.

You're welcome to update the changelog if you want, otherwise I will update it once I prepare the next release. 

Seems like I was able to fix the CI problems. If you merge the current master into your branch then the compilation of  `openblas-src` should work again and the clippy errors should be gone.

**Comment by dariogoetz** [comment]
Thanks for fixing the CI. I have updated the changelog, adding a line about the fix.

**Comment by stefan-k** [comment]
Thanks a lot once more for this PR!

**Pull request merged**
