### PR TITLE
MAINT Lint with CircleCI

### PR DESCRIPTION
**Pull request by rth**
Add a CircleCI config that runs,
 - `cargo fmt`
 - `cargo clippy`: failures are allowed, and one would need to actually look at the logs to see warnings / errors there.

### CODE REVIEW

**Comment by rth** [comment]
Also @stefan-k you would need to enable "Run on PRs" under "Advanced Settings" of CircleCI settings for this project, for it to actually run here. Otherwise it would only run for existing branches of this repo.

**Comment by stefan-k** [comment]
I've set "Build forked pull requests" to "on". Is this correct?

**Comment by rth** [comment]
Yes, thanks!

**Comment by stefan-k** [comment]
Thanks for your great work! CircleCI seems to work fine, can I merge this?

**Comment by rth** [comment]
It's good to merge, on my side.  Thanks!

**Pull request merged**
