### PR TITLE
Replace assert! macros with macros from approx crate

### PR DESCRIPTION
**Pull request by rpopplewell**
(https://github.com/argmin-rs/argmin/issues/278) Replaces all `assert!` macros that directly compare `f64s` in tests. `approx::assert_relative_eq(f64::NAN, f64::NAN)` does not pass, so I skipped those.

### CODE REVIEW

**Comment by stefan-k** [comment]
Thanks for the huge effort! I haven't done a thorough review yet, but I can already say one thing: Whenever I used `.to_ne_bytes()`, I did it deliberately, because I want to make sure that they are *exactly* the same. Using `to_ne_bytes()` better communicates the intention; however, I probably should have also made a comment about this somewhere.

**Comment by rpopplewell** [comment]
Ah my bad, I assumed I'd continue the pattern that was there for existing approx comparisons. Let me know what to change though (besides the rust fmt of course)

**Comment by stefan-k** [comment]
I just had a bit more detailed look at it and I'm afraid that most of the work you have done is not needed and this is entirely my fault. I was not precise enough in the issue you linked (#278). Actually, what I meant was the test code in argmin-math and not in argmin. I should have specified that, I am very sorry!! 
 
I really appreciate the effort you put in, and if you are still interested in doing the changes to argmin-math then I'm happy to review another PR.

**Comment by rpopplewell** [comment]
Ah I should've asked I suppose. You can close this and I'll see to getting around to it later. It's a cool project and it helps me learn rust, so no worries!

**Pull request closed without merging**
